### ISSUE TITLE
Create a `<wc-blink>` web component

### ISSUE THREAD

**Issue by evanplaice** [evanplaice/evanplaice#60]
Horrible idea. Building it per request 😂
https://twitter.com/ThugDebugger/status/1174405066075324416?s=20

Spec:

This'll use the polyfill implementation directly from the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blink)

```css
blink {
  -webkit-animation: 2s linear infinite condemned_blink_effect; // for Safari 4.0 - 8.0
  animation: 2s linear infinite condemned_blink_effect;
}
@-webkit-keyframes condemned_blink_effect { // for Safari 4.0 - 8.0
  0% {
    visibility: hidden;
  }
  50% {
    visibility: hidden;
  }
  100% {
    visibility: visible;
  }
}
@keyframes condemned_blink_effect {
  0% {
    visibility: hidden;
  }
  50% {
    visibility: hidden;
  }
  100% {
    visibility: visible;
  }
}

```

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blink
